name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub Stats (Dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: t3chn
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow
          filename: assets/github-stats.svg
          config_display: large
          config_output: svg

      - name: GitHub Stats (Light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: t3chn
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow
          filename: assets/github-stats-light.svg
          config_display: large
          config_output: svg

      - name: Languages (Dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: t3chn
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          filename: assets/languages.svg

      - name: Languages (Light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: t3chn
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          filename: assets/languages-light.svg
